{% set name = "sudachidict-core" %}
{% set version = "20260428" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace( '-', '_' )}}-{{ version }}.tar.gz
  sha256: 5492112a4a0999116cb8e4327b5ad3263167e9451fc8b50e8e7b83fc00bd2d98

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - sudachipy >=0.5,<0.7

test:
  imports:
    - sudachidict_core
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://github.com/WorksApplications/SudachiDict
  dev_url: https://github.com/WorksApplications/SudachiDict
  doc_url: https://github.com/WorksApplications/SudachiDict
  summary: Sudachi Dictionary for SudachiPy - Core Edition
  description: Sudachi Dictionary for SudachiPy - Core Edition
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-2.0.txt
    - sudachidict_core/resources/LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - skupr-anaconda
